name: tubdown
description: "YouTube Video, Audio, Playlist Downloader"

publish_to: 'none'

version: 1.4.0+1

environment:
  sdk: '>2.12.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.4
  youtube_explode_dart: ^2.2.1
  permission_handler: ^11.3.1
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_local_notifications: ^17.2.2
  flutter_ffmpeg: ^0.4.0
  video_player: ^2.5.2
  audioplayers: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/opening.png

flutter_launcher_icons:
  android: true
  image_path: "assets/images/opening.png"
  adaptive_icon_background: "#0099f6"
  adaptive_icon_foreground: "assets/images/opening.png"

flutter_native_splash:
  color: "#0099f6"
  image: assets/images/opening.png
  android: true